### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by msom** [collective/collective.geo.mapwidget#19]
Would it be possible to make a release with the updated german translations?

And also for:
- https://github.com/collective/collective.geo.mapwidget
- https://github.com/collective/collective.geo.settings

**Comment by do3cc** [comment]
@gborelli I see that you are currently the only one who can make releases. If you give me release rights, I'd love to do a release myself. There is at least one real fix in the code that warrants a release.

**Comment by gborelli** [comment]
Just released
- https://pypi.python.org/pypi/collective.geo.mapwidget - v 2.2
- https://pypi.python.org/pypi/collective.geo.settings - v 3.1

**Comment by msom** [comment]
Great, thanx!
