### ISSUE TITLE
Google Base Layers Not Displayed Unless Satellite Selected

### ISSUE THREAD

**Issue by l34marr** [collective/collective.geo.mapwidget#21]
Fresh Plone 4.3.7 installation, plone.app.contenttypes and collective.geo.bundle enabled, content types migrated with @@atct_migrator, that means I'd like to make sure at least Dexterity types work with collective.geo.

By default, in **Geo Settings** map layers are OpenStreetMap, Terrain (Google), Hybrid (Google), Satellite (Google), Google.
![00](https://cloud.githubusercontent.com/assets/56113/13420749/b1f9563c-dfc3-11e5-8beb-623869c16448.png)

We want to use Google as default base layer, but it shows blank map.
![01](https://cloud.githubusercontent.com/assets/56113/13421338/ba96ed4a-dfc8-11e5-81a8-026ee20b839c.png)

If we select Satellite (Google), and it works well to show the map. But it shows blank map if Satellite (Google) is not selected as the first base layer.
![02](https://cloud.githubusercontent.com/assets/56113/13421432/41faa5d8-dfc9-11e5-9597-d77e2f757ecc.png)

What's the cause for this annoying issue and how to fix it?

**Comment by maethu** [comment]
We solved this issue by using a more recent openlayers version --> https://github.com/4teamwork/ftw.openlayerhotfix

**Comment by maethu** [comment]
I'll check collective.geo.openlayers.. probably I can implement a more recent openlayers.js version

**Comment by maethu** [comment]
@l34marr I opened a PR for c.g.openlayers 3.x branch --> https://github.com/collective/collective.geo.openlayers/pull/6

This should fix the display issue. 

I'm currently testing it (I may did something wrong, updating openlayers). Feel free to test it too.

**Comment by maethu** [comment]
I released collective.geo.openlayers 3.2b1. This fixes this Bug.
