### ISSUE TITLE
The maps api version used is retired

### ISSUE THREAD

**Issue by pnicolli** [collective/collective.geo.mapwidget#25]
I am using `collective.geo.mapwidget == 2.4`, the Google Map is not showing and I'm getting this warning in the console:
```
Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
```

Google explains [here](https://developers.google.com/maps/documentation/javascript/versions) that versions 3.0 - 3.25 of the API have been retired, and my understanding is that we are using version 3.2 ([source code](https://github.com/collective/collective.geo.mapwidget/blob/master/src/collective/geo/mapwidget/browser/geosettings_view.py#L13))

I also tried manually changing the version that we ask for to `v=3` as explained in their docs, the warning disappears but the map is still not showing. There might have been some other api changes from Google side, I will try to hack more as soon as I can, to see if I can discover some other useful info, but meanwhile I thought I'd post this, in case someone else faced this same problem.

**Comment by pbauer** [comment]
@pnicolli these issues are fixes with https://github.com/collective/collective.geo.mapwidget/pull/28. But google maps still does not work.
